defaults:
  - _self_
  - data: mnist
  - model: mnist
  - trainer: default
  - experiment: null
  - paths: default
  - hydra: default
  - logger: [wandb]
  - callbacks: default

task_name: train_on_mnist
