defaults:
  - _self_
  - model: mnist
  - data: mnist
  - logger: [wandb]
  - callbacks: default
  - trainer: default
  - paths: default
  - hydra: default
  - experiment: null

task_name: train

train: True
test: True

ckpt_path: null

seed: null
